### ISSUE TITLE
Nest.js v8 Dependency Issues

### ISSUE THREAD

**Issue by j** [Davide-Gheri/nestjs-mercurius#177]
I'm getting various issues installing the latest versions of Nest.js & Mercurius.

One being: https://github.com/nestjs/graphql/blob/master/package.json#L80

I'm not sure `apollo-server-core` should even be a peerDependency.  Perhaps this library needs to make all the optional dependencies optional using "peerDependenciesMeta"?

**Comment by Davide-Gheri** [comment]
well unfortunately `apollo-server-core` is not optional, because `@nestjs/graphql` uses it (using `@nestjs/graphql` directly requires either `apollo-server-express` or `apollo-server-fastify` that has a direct dependency with `apollo-server-core`)

we could add `apollo-server-core` as a depencency keeping aligned with the peerDep defined on `@nestjs/graphql`, or simply modifying the install instructions including it
