### ISSUE TITLE
federation + subscription doesn't work with external type

### ISSUE THREAD

**Issue by rhyek** [Davide-Gheri/nestjs-mercurius#277]
I have two services each with their federated graph. The first (main) publishes queries and mutations and a `Message` type, the second (subscriptions) publishes one subscription that returns a `Message` object. They are both connected through a redis pubsub.

For some reason, when subscribing (via apollo client in a react app) to that subscription through a mercurius gateway, the websocket receives a frame with payload `{"type":"error","id":"1","payload":"service.createSubscription is not a function"}` and the subscription is never connected and thus never receives any messages;

I have a reproduction here: https://github.com/rhyek/graphql-federation-subscriptions-tests

federated `Message` type: https://github.com/rhyek/graphql-federation-subscriptions-tests/blob/mercurius/apps/nest-apps/libs/types/src/message.type.ts
representative `Message` class: https://github.com/rhyek/graphql-federation-subscriptions-tests/blob/mercurius/apps/nest-apps/apps/gql-subscriptions/src/message.resolver.ts#L13
gateway, main, and subscription nestjs apps at: https://github.com/rhyek/graphql-federation-subscriptions-tests/tree/mercurius/apps/nest-apps/apps

Btw, if I define another subscription that returns some new type owned by the subscriptions service, it works and the client can connect with no issues.

**Comment by Davide-Gheri** [comment]
Hi @rhyek , I checked your reproduction repo and indeed I managed to see the error.
I dug into the source code of Mercurius (as I suppose is a problem with mercurius itself) and found out that the gateway "thinks" that the `messageAdded` Subscription belongs to the `messages` service.

The problem is not in subscriptions alone, but all types are affected.
You cannot define Queries/Mutations/Subscriptions that returns types defined in another service, even if you `@extend` them.

As a simplified example:

posts service
```
type Post @key(fields: "id") {
  id: ID!
  title: String!
}

extend type Query {
  posts: [Post!]!
}
```

comments service
```
type Comment @key(fields: "id") {
  id: ID!
  message: String!
  postId: String!
}

extend type Post @key(fields: "id") {
  id: ID! @external
  comments: [Comment!]!
}

extend type Query {
  postComments(postId: ID!): [Comment!]!
}
```
Since here everything should work. We are defining 2 services each one with 2 types and 2 queries that returns types defined inside the service.

If we add this Query to the comment service:
```
post(postId: ID!): Post!
```
even if we are extending `Post` type, the gateway tries to resolve the query in the service where the Post type belongs (posts service), returning an error (Cannot query field \"post\" on type \"Query\".).

The same logic seems to apply to Subscriptions, the gateway tries to create a subscription connection with a service that doesn't have a subscription client

**Comment by rhyek** [comment]
@Davide-Gheri i sort of expected this to be an upstream issue, but decided to open the issue here just in case. My experience is mostly with `@nestjs/graphql`, however, and for now we will be sticking with apollo so I don't expect to have time to open an issue with native use of mercurius on their github.

You can close this issue if you need to. Thanks.
