### ISSUE TITLE
Support mercurius 9.x

### ISSUE THREAD

**Issue by akaNightmare** [Davide-Gheri/nestjs-mercurius#315]

**Comment by Davide-Gheri** [comment]
Mercurius 9 requires graphql@16, while @nestjs/graphql (which this library heavily relies) still uses graphql@15, so this upgrade is not possible.

Said that, something is moving in the official @nestjs/graphql repo, precisely this: https://github.com/nestjs/graphql/pull/1893

When the PR will be merged and released, this library won't have any reason to exist since mercurius support will be native

**Comment by akaNightmare** [comment]
@Davide-Gheri https://github.com/nestjs/graphql/pull/1893 has been merged
